<a href="https://colab.research.google.com/github/ArvidLev/PCA/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principal Component Analysis
For this project I am creating a PCA function. I will go over the theory of it but I will be using the numpy library to help me compute.<br>
The goal of PCA is dimensionality reduction while maximizing the variance.

## Theory

Consider $\{x_n\}, n = 1,2,...,N, x_n \in \mathbb{R}^{D}$ <br>
Goal: To project onto a flat surface with dimension $N < D$ while maximizing the variance of the projected data. <br>
Start with $N = 1$ defined by a single vector $u_1 \in \mathbb{R}^D$ which we can assume, without loss of generality, is unit lenght such that $u_1u_1^T = 1$. <br>
Then $x_n$ is projected onto a scalar value $u_1^Tx_n$. The mean of the projected data is then $u_1^T\bar{x}$ where $\bar{x} = \frac{1}{N} \sum_{n = 1}^N x_n$. Now we find the projected variance by $\frac{1}{N} \sum_{n = 1}^N (u_1^Tx_n - u_1^T\bar{x})^2 = u_1^TSu_1$ where $S = \frac{1}{N} \sum_{n = 1}^N (x_n - \bar{x})(x_n - \bar{x})^T = cov(X)$. <br>
We want to maximize the projected variance which gives us the optimization problem,<br> 
Maximize $u_1^TSu_1$ such that $u_1^Tu_1 = 1$. We will introduce Lagrange multiplier for the constraint. This give us, <br>
max $u_1^TSu_1 + \lambda_1(1 - u_1^Tu)$<br>
Taking the derivative with respect to $u_1$ and setting to 0 we get, <br>
$2Su_1 - 2\lambda_1u_1 = 0$<br>
$Su_1 = \lambda_1u_1$ <br>
This is an eigen-problem with $(\lambda_1, u_1)$ eigen-pair. <br>
So in order to maximize the variance we need to find the dominant eigen-pair which is the eigen-pair with the largest eigenvalue. <br>
This means that the projected variance will be the largest when $u_1$ is set to the eigenvector with the largest eigenvalue of the covariance matrix.



So in order to project for dimensions N > 1, we take the N largest eigenvectors and project our data onto them.

## Coding

In [ ]:
import numpy as np

First, lets create a matrix that will be our data. Lets use a 10x10 matrix.

In [ ]:
X = np.random.randint(20,80,100).reshape(10,10)
X

array([[30, 26, 51, 68, 36, 38, 58, 75, 38, 39],
       [34, 76, 37, 75, 63, 57, 62, 62, 35, 36],
       [23, 70, 38, 56, 49, 30, 57, 68, 31, 53],
       [34, 36, 24, 45, 29, 75, 25, 68, 63, 42],
       [41, 51, 31, 78, 56, 61, 72, 53, 41, 45],
       [22, 46, 79, 44, 45, 45, 43, 34, 39, 21],
       [72, 51, 48, 56, 49, 57, 39, 75, 73, 20],
       [50, 44, 77, 46, 24, 26, 71, 56, 45, 33],
       [24, 73, 23, 76, 64, 72, 23, 74, 59, 34],
       [20, 27, 64, 63, 38, 30, 34, 34, 46, 33]])

Now we find the covariance matrix.

In [ ]:
cov = np.cov(X, rowvar = False)
cov

array([[ 257.33333333,   -3.88888889,   11.66666667,  -28.33333333,
         -23.33333333,   39.55555556,   61.88888889,   94.        ,
         124.        ,  -60.66666667],
       [  -3.88888889,  328.88888889, -164.44444444,   87.66666667,
         191.88888889,   96.44444444,   30.        ,   88.44444444,
         -30.77777778,   30.88888889],
       [  11.66666667, -164.44444444,  419.06666667, -143.93333333,
        -140.17777778, -269.8       ,   94.02222222, -202.08888889,
         -71.        , -112.35555556],
       [ -28.33333333,   87.66666667, -143.93333333,  175.78888889,
         130.98888889,   66.47777778,   42.24444444,   47.85555556,
         -32.77777778,   37.31111111],
       [ -23.33333333,  191.88888889, -140.17777778,  130.98888889,
         184.9       ,  107.52222222,   -7.46666667,   35.58888889,
         -15.55555556,    3.02222222],
       [  39.55555556,   96.44444444, -269.8       ,   66.47777778,
         107.52222222,  318.32222222, -152.15555556,  106

Now we find the eigen-pairs using a numpy function.

In [ ]:
eigen_val, eigen_vec = np.linalg.eigh(cov)
sorted_index = np.argsort(eigen_val)[::-1]
sorted_eigenval = eigen_val[sorted_index]
sorted_eigenvec = eigen_vec[:,sorted_index]

In [ ]:
eigen_val

array([4.74409975e-14, 1.99140058e+00, 1.15133140e+01, 4.33784930e+01,
       9.96125047e+01, 1.55720857e+02, 2.59868810e+02, 3.79579252e+02,
       5.71076180e+02, 1.01819252e+03])

In [ ]:
eigen_vec

array([[-0.32756988, -0.30013247, -0.21748125,  0.30883484, -0.03844625,
         0.14912124, -0.17412868,  0.74318829,  0.22789381, -0.0405086 ],
       [-0.02672686, -0.11619617,  0.35823998,  0.11613227, -0.16398036,
        -0.5113717 , -0.52491849,  0.07163991, -0.39582459, -0.34383451],
       [-0.44222313,  0.29674632,  0.20576388, -0.34066635,  0.14348761,
        -0.03551026, -0.41571357,  0.05839385,  0.05869327,  0.59704757],
       [-0.17773112, -0.16045467,  0.45887596,  0.06345594,  0.55012089,
         0.54135065,  0.02822424, -0.03379907, -0.28413279, -0.22295335],
       [-0.01685146,  0.41954237, -0.64178801,  0.00994418,  0.22999449,
         0.18666454, -0.40552925, -0.08478331, -0.26523527, -0.28631529],
       [-0.25089319,  0.06497143,  0.12877577, -0.4756336 , -0.52210669,
         0.35229936, -0.08972148, -0.06944998,  0.24860433, -0.4675823 ],
       [ 0.355089  ,  0.26923031,  0.10644928, -0.15777253, -0.3114282 ,
         0.26454448,  0.14354118,  0.50151146

Now we project our data onto the N number of eigenvectors. For this example, lets use N = 5.

In [ ]:
eigen_vectors = eigen_vec[-5:]
projected_X = np.dot(eigen_vectors, X)

In [ ]:
projected_X

array([[-45.50084283, -22.22377094, -39.128642  , -70.38595628,
        -33.72742215, -56.68263462, -56.1269913 , -62.18795699,
        -57.41555596, -47.75782023],
       [ 36.41868055,  23.31113959,  85.33624673,  33.30003838,
         17.08051167,   1.62707299,  63.92433629,  38.1859177 ,
         24.28675203,  21.77948127],
       [ 29.70973321,  17.15125713,  -5.84599008,  14.28659816,
          9.95702749,  -5.69455734,  32.03700162,  12.7003901 ,
         -1.16929607,  -0.9689285 ],
       [ 61.42536142, 128.34891804,  71.78941848, 137.03191077,
        105.39593048, 115.87803533, 104.56047654, 143.61629443,
         89.09377527,  85.6156584 ],
       [ 21.13416618,  17.47511731, -15.37426467, -11.80395425,
          3.29593588,  17.47672765, -12.24839971,   4.28337632,
         16.25931199,  -5.83983512]])

## Function
Now lets put everything together into a function.

In [ ]:
def PCA(X, num_components = 0):
  if num_components == 0:
    num_components = len(X) #This gives us N = D projection
  cov = np.cov(X, rowvar = False)
  eigen_val, eigen_vec = np.linalg.eigh(cov)
  sorted_index = np.argsort(eigen_val)[::-1]
  sorted_eigenval = eigen_val[sorted_index]
  sorted_eigenvec = eigen_vec[:,sorted_index]
  eigen_vectors = eigen_vec[-num_components:]
  projected_X = np.dot(eigen_vectors, X)
  return projected_X
  

In [ ]:
PCA(X, 5)

array([[-18.94753588, -20.31310808, -38.39264664, -11.96549655,
         -4.74087782,  22.85419159,  -1.76442085, -15.55914334,
         12.62152778, -19.05283023],
       [ 59.08391246,  60.9353822 ,  49.10347996,  56.91153725,
         61.50652529,  73.25043538,  77.64481871,  79.55876167,
         71.72065922,  83.62136532],
       [ 10.19160121,  27.45348611,   8.50188698,  23.00728555,
          0.71367103,  37.1730505 ,  18.60750998,  -5.0261363 ,
         12.56018307,  19.42343253],
       [ 97.8349777 ,  89.13696084,  82.14440077, 109.7211591 ,
         80.99472638,  85.77230115,  88.96343673,  40.74948208,
         78.48135773,  56.04167883],
       [ 52.92916182,  56.70466666,  68.2429557 ,  43.56584498,
         46.85116433,  52.05115317,  58.31781937,  55.09771571,
         83.87460142,  49.27127221]])